data_dir: 'output/'
#^output is the directory

#directory where package stores Metadata and RV Database by defult it is where EZRV is installed
default_directory : '/Users/Sarah/Wave21/EZRV/EZRV'

#format of your csv
input_dict : {"Time": "time",
           "RV" : "RV",
           "Uncertainty" : "uncert",
           "Observatory_Site" : "obs_site",
           "Star_Name" : "name",
           "Time_Convention" : "constant:JD",
           "Reference" : "constant:Teske et al. 2021(ApJS 256 33)",
           "Instrument" : "Instr",
           "Wavelength_Calibration_Technique" : "wavelength_calib_technique" ,
           "Source" : "constant:MTS",
           "Halpha_Index" :"halpha",
           "Halpha_Index_Error":"halpha_e",
           "Full_Width_Half_Maximum":"FWHM",
           "Bisetor" : "bisector",
           "Signal_to_noise_ratio_in_order_55":"sig_to_noise_ratio_in_order_55",
           "Exposure_Time":"exp_time",
           "Airmass":"airmass",
           "Barycentric_Earth_Radial_Velocity":"barycentric_earth_rv"}

retrieve_data : 'starname for desired data'



#change dict to be from example file to our new structure
