data_dir: 'output/'
#^output is the directory

#directory where package stores Metadata and RV Database by defult it is where EZRV is installed
default_directory : '/Users/Sarah/Wave21/EZRV/EZRV'

#format of your csv
input_dict : {"Time": "time",
           "RV" : "rv",
           "Uncertainty" : "uncert",
           "Observatory_Site" : "obs_site",
           "Star_Name" : "star",
           "Time_Convention" : "time_system",
           "Reference" : "reference",
           "Instrument" : "instr",
           "Wavelength_Calibration_Technique" : "constant:ThAr" ,
           "Source" : "source",
           "Halpha_Index" :"halpha",
           "Halpha_Index_Error":"halpha_e",
           "Full_Width_Half_Maximum":"FWHM",
           "Bisetor" : "bisector",
           "Signal_to_noise_ratio_in_order_55":"sig_to_noise_ratio_in_order_55",
           "Exposure_Time":"exp_time",
           "Airmass":"constant:NaN",
           "Barycentric_Earth_Radial_Velocity":"barycentric_earth_rv"}

retrieve_data : 'starname for desired data'



#change dict to be from example file to our new structure
